# Generated by Django 5.0.3 on 2026-08-02 09:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('career_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('last_crawl_ok', models.BooleanField(default=True)),
                ('last_crawl_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=50, unique=True)),
                ('slack_channel_id', models.CharField(blank=True, default='', max_length=50)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('notify_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slack_user_id'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('meta', models.CharField(blank=True, default='', max_length=255)),
                ('meta_label', models.CharField(blank=True, default='', max_length=20)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('is_open', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='Crawling_App.company')),
            ],
            options={
                'ordering': ['-first_seen_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Crawling_App.jobposting')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Crawling_App.subscriber')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='Crawling_App.subscriber')),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company', 'is_open'], name='Crawling_Ap_company_74aa5b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['-first_seen_at'], name='Crawling_Ap_first_s_934082_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(fields=('company', 'fingerprint'), name='uniq_posting_per_company'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('subscriber', 'posting'), name='uniq_notification'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('subscriber', 'text'), name='uniq_keyword_per_subscriber'),
        ),
    ]
