# Generated by Django 5.0.3 on 2026-09-22 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawling_App', '0002_company_paused'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='기업/사이트 이름')),
                ('url', models.URLField(max_length=1000, verbose_name='채용공고 페이지 주소')),
                ('note', models.TextField(blank=True, default='', verbose_name='요청 메모')),
                ('status', models.CharField(choices=[('pending', '대기'), ('in_progress', '진행 중'), ('done', '완료'), ('rejected', '반려')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='관리자 답변')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_requests', to='Crawling_App.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
